name: asuka
description: Show Snackbars, dialogs, ModalSheets and more in a single provider. Simple and Clean.
version: 2.1.0
homepage: https://github.com/Flutterando/asuka

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:    
  flutter:
    sdk:  flutter
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  

flutter:
